#pragma once
#include <stddef.h>
namespace sbn::v3::native_policy {
// Generated by tools/generate_tuning.py from config/tuning/native-selection.json.
inline constexpr size_t newton_single_worker_below = 8192; // rung precision words
inline constexpr size_t newton_middle_band_max = 262160; // rung precision words including caller guards
inline constexpr unsigned newton_middle_workers = 8; // workers
inline constexpr size_t value_parallel_words = 1048576; // words
inline constexpr size_t small_model_max_words = 4194304; // input words
inline constexpr double deep_ns_per_work = .65; // nanoseconds per calibrated W16 work unit
inline constexpr double memory_trade_time_ratio = 1.01; // dimensionless ratio
inline constexpr double memory_trade_resident_ratio = .875; // dimensionless ratio
inline constexpr double scalar_ring_ns_per_word = .15; // nanoseconds per ring word
inline constexpr double scalar_input_ns_per_word = 1.; // nanoseconds per input word
static_assert(newton_middle_workers > 0 && newton_middle_workers <= 32);
static_assert(memory_trade_time_ratio >= 1 && memory_trade_resident_ratio > 0 && memory_trade_resident_ratio <= 1);
}
