#pragma once
#include <stddef.h>
namespace sbn::v3::p48_geometry {
// Generated by tools/generate_tuning.py; measured rules in native-geometry.json.
inline constexpr int linear_deep_log_m = 24;
inline constexpr int linear_deep_log_c = 13;
inline constexpr int linear_row_log = 11;
inline constexpr int linear_min_log_c = 8;
inline constexpr int linear_middle_max_log_c = 11;
inline constexpr int lattice_min_log_m = 18;
inline constexpr int lattice_max_log_m = 21;
inline constexpr int lattice_fill_percent = 92;
inline constexpr int near_full_numerator = 19;
inline constexpr int near_full_denominator = 20;
inline constexpr int full_row_log = 7;
inline constexpr int truncated_row_log = 10;
struct ColumnTransfer {
    unsigned workers, first_np, last_np, from_column_log, from_row_log, to_column_log;
    size_t minimum_row_bytes;
};
inline constexpr ColumnTransfer column_transfers[]{
    {32,6,10,13,11,12,0},
    {32,9,10,11,12,12,67108864}
};
// The second class transfers only when inverse-row vector payload alone
// exceeds the balanced machine LLC. These are execution-cost proposals;
// callers recheck arithmetic legality and preserve explicit/cache geometry.
inline unsigned smt_column_log(unsigned workers,unsigned np,unsigned column_log,
                                unsigned row_log,size_t live_slots) {
    const size_t row_bytes=size_t(workers)*np*live_slots*64;
    for(const auto &r:column_transfers)
        if(workers==r.workers && np>=r.first_np && np<=r.last_np &&
           column_log==r.from_column_log && row_log==r.from_row_log &&
           row_bytes>r.minimum_row_bytes)return r.to_column_log;
    return column_log;
}
struct RowChoice { int log_m, row_log, force_full, uncapped; };
inline RowChoice choose_rows(bool linear, bool cyclic, int leaf, int log_m,
                             int row_log, size_t need, int exact, int force_full) {
    int uncapped = exact;
    const int smallest_log_m = log_m;
    if (row_log <= 0 && linear && leaf == 8) {
        int log_c;
        if (log_m >= linear_deep_log_m) log_c = linear_deep_log_c;
        else {
            log_c = log_m - linear_row_log;
            if (log_c < linear_min_log_c) log_c = linear_min_log_c;
            if (log_c > linear_middle_max_log_c) log_c = linear_middle_max_log_c;
        }
        if (log_m < log_c + linear_row_log) log_m = log_c + linear_row_log;
        const size_t smallest_n = size_t(8) << smallest_log_m;
        if (smallest_log_m >= lattice_min_log_m && smallest_log_m <= lattice_max_log_m &&
            need * 100 >= smallest_n * lattice_fill_percent) {
            log_m = smallest_log_m; log_c = linear_middle_max_log_c; force_full = 1;
        }
        row_log = log_m - log_c; uncapped = 1;
    }
    if (row_log <= 0) {
        const size_t n = 8 * (leaf == 8 ? 1 : size_t(leaf)) * (size_t(1) << log_m);
        const bool fullish = cyclic || need * near_full_denominator > n * near_full_numerator;
        row_log = fullish ? full_row_log : truncated_row_log;
    }
    return {log_m, row_log, force_full, uncapped};
}
}
