#!/usr/bin/env python3
"""Reproducible, correctly rounded fixed FFT constants (development only)."""
from pathlib import Path
import mpmath as mp
def body(dps):
    mp.mp.dps=dps
    lines=['#pragma once','// Generated by tools/gen_pq_roots.py at 100/160 decimal digits.',
           'namespace sbn::v3::pq16 {']
    for m in (3,5,7):
        for suffix,func in [('RE',mp.cos),('IM',lambda a:-mp.sin(a))]:
            values=[]
            for k in range(m):
                v=func(2*mp.pi*k/m)
                if k==0:v=mp.mpf(1 if suffix=='RE' else 0)
                if m==3 and suffix=='RE' and k:v=mp.mpf('-0.5')
                values.append(float(v).hex())
            lines.append(f'inline constexpr double PQ16_W{m}_{suffix}[{m}] = {{'+', '.join(values)+'};')
    vals={'PQ16_W5_CM':mp.sqrt(5)/4,'PQ16_W5_S1P':mp.sin(2*mp.pi/5)+mp.sin(4*mp.pi/5),
          'PQ16_W5_S2M':mp.sin(4*mp.pi/5)-mp.sin(2*mp.pi/5)}
    for name,value in vals.items():lines.append(f'inline constexpr double {name} = {float(value).hex()};')
    def ld(v):
        if not v:return '0x0p+0L'
        exponent=int(mp.floor(mp.log(v,2)));mantissa=int(mp.floor(v*mp.power(2,68-exponent)))
        return f'0x{mantissa:x}p{exponent-68:+d}L'
    # All supported pow2 roots reduce to this 2^19 grid. Splitting its
    # first octant at eight bits needs only 513 extended complex seeds.
    lines.append('inline constexpr unsigned PQ16_ROOT_GRID_LOG2 = 19;')
    for name,count,denom in [('COARSE',257,2048),('FINE',256,524288)]:
        lines.append(f'inline constexpr long double PQ16_ROOT_{name}[{count}][2] = {{')
        for k in range(count):
            angle=2*mp.pi*k/denom;lines.append('    {'+ld(mp.cos(angle))+', '+ld(mp.sin(angle))+'},')
        lines.append('};')
    lines.append('}')
    return '\n'.join(lines)+'\n'
a=body(100);assert a==body(160)
path=Path(__file__).resolve().parents[1]/'src/backend/pq16/roots.hpp'
path.write_text(a)
