#!/usr/bin/env python3
"""Generate Q56 log2 floors using exact rational bounds, no floating point.

For 1<=x<=2, log(x)=2*sum r^(2j+1)/(2j+1), r=(x-1)/(x+1).
The omitted positive tail is below 2*r^(2k+1)/((2k+1)*(1-r*r)).
The lower/upper ratios to log(2) must select the same Q56 integer.
"""
import argparse
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
DEST=ROOT/'src/radix/log2_bounds.hpp'
def ln_bounds(x,k):
    r=(x-1)/(x+1);term=r;total=Fraction(0)
    for j in range(k):total+=term/(2*j+1);term*=r*r
    lo=2*total
    return lo,lo+2*term/((2*k+1)*(1-r*r))
def floor_log(n):
    if n<2:return 0
    e=n.bit_length()-1
    for k in (16,32,64,128):
        l2,u2=ln_bounds(Fraction(2),k);lo,hi=ln_bounds(Fraction(n,1<<e),k)
        a=(Fraction(e)+lo/u2)*(1<<56);b=(Fraction(e)+hi/l2)*(1<<56)
        a=a.numerator//a.denominator;b=b.numerator//b.denominator
        if a==b:return a
    raise ArithmeticError(n)
def content():
    values=[floor_log(n) for n in range(65)]
    return ('// Generated by tools/generate_radix_bounds.py, proved with rational series bounds.\n'
            '#pragma once\n#include <stdint.h>\nnamespace sbn::v3::radix {\n'
            'inline constexpr uint64_t log2_floor_q56[65] = {\n'+
            ''.join(f'    0x{x:016x}ULL, // {n}\n' for n,x in enumerate(values))+
            '};\n} // namespace sbn::v3::radix\n')
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');args=ap.parse_args();text=content()
    if args.check:
        if not DEST.exists() or DEST.read_text()!=text:raise SystemExit('radix logarithm bounds are stale')
        print('OK: exact Q56 logarithm bounds for bases 1..64')
    else:DEST.write_text(text)
if __name__=='__main__':main()
