#!/usr/bin/env python3
"""Generate the immutable all-base power prefix using exact integer arithmetic."""
import argparse
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
DEST=ROOT/'src/radix/power_bank.cpp'
def content():
    words=[];entries=[]
    for odd in range(3,64,2):
        value=odd**64
        for level in range(9):
            start=len(words);n=(value.bit_length()+63)//64
            words.extend((value>>(64*j))&((1<<64)-1) for j in range(n))
            words.extend([0]*(((n+15)//8)*8-n))
            entries.append((start,len(words)-start))
            value*=value
    lines=['// Generated by tools/generate_radix_powers.py; exact integers, no runtime initialization.',
           '#include "radix/power_bank.hpp"','namespace sbn::v3::radix {','static_assert(fixed_power_levels==9);','namespace {',
           'struct Entry { uint32_t offset,capacity; };',
           f'alignas(64) constexpr uint64_t words[{len(words)}] = {{']
    lines+=['    '+','.join(f'0x{x:016x}ULL' for x in words[j:j+4])+',' for j in range(0,len(words),4)]
    lines+=['};',f'constexpr Entry entries[{len(entries)}] = {{']
    lines+=['    {'+str(a)+','+str(b)+'},' for a,b in entries]
    lines+=['};','}',
            'FixedPower fixed_power(unsigned odd,unsigned level) noexcept {',
            '    if(odd<3 || odd>63 || !(odd&1) || level>=fixed_power_levels)return {};',
            '    const auto &e=entries[((odd-3)/2)*fixed_power_levels+level];',
            '    return {words+e.offset,e.capacity};','}',
            'size_t fixed_power_bytes() noexcept { return sizeof(words)+sizeof(entries); }','}']
    return '\n'.join(lines)+'\n'
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();text=content()
    if a.check:
        if not DEST.exists() or DEST.read_text()!=text:raise SystemExit('radix power constants are stale')
        print('OK: immutable power prefix for all 31 odd bases')
    else:DEST.write_text(text)
if __name__=='__main__':main()
