#pragma once
// Generated by tools/generate_tuning.py from config/tuning/native-short.json.
#include <algorithm>
#include <cmath>
#include "backend/pq16/cost_model.hpp"
namespace sbn::v3 {
// Prepared B=16/W native products, Clang 21.1.8 / Zen5 Strix Halo.
// Alternating fine-grid lengths held out; model only ranks legal candidates.
// Calibration SHA-256: 1fb61dcf8842d6d385761b848b0193003b0b679da965f4a2e5370f1da0e46139
template<size_t N> inline double short_dot(const double (&f)[N],const double (&c)[N]){double v=0;for(size_t k=0;k<N;++k)v+=f[k]*c[k];return v;}
// Below capacity the clamped cache term is exactly zero; no logarithm is
// needed. This preserves the model while keeping small plan quotes cheap.
inline double short_log_pressure(double ratio){return ratio>1.?std::log2(ratio):0.;}
inline double scalar_product_cost(size_t an,size_t bn,unsigned workers){
    const double size=an+bn,work=double(an)*bn,w=workers,pressure=std::max(0.,std::log2(16/w));
    const double f[]={1,work,work*pressure,size,size*std::max(0.,std::log2(16*size/(768*1024))),size*std::max(0.,std::log2((16/w)*16*size/(48*1024*1024))),size*pressure};
    constexpr double co[]={0,0.2895891859551134,0.052564791501154819,0,0.14321369903795178,2.2405273643243753,0.1569145071223659};return short_dot(f,co)*(std::min(an,bn)==2 && std::max(an,bn)>=8192?.90:1.);
}
inline double u52_product_cost(size_t an,size_t bn,unsigned workers){
    const double x=(64*std::max(an,bn)+51)/52,y=(64*std::min(an,bn)+51)/52,w=workers;
    constexpr double a=1.584962500721156,b=1.464973520717927;
    double work=y<96?y*y:y<618?std::pow(96.,2-a)*std::pow(y,a):std::pow(96.,2-a)*std::pow(618.,a-b)*std::pow(y,b);
    work*=y?x/y:0;const double f[]={1,std::log2(w)+1,x+y,work,work*short_log_pressure(16/w),(an+bn)*short_log_pressure(36.*std::max(an,bn)/(768*1024)),(an+bn)*short_log_pressure((16/w)*36.*std::max(an,bn)/(48*1024*1024))};
    // 2026-09-09: the W1 terms refit on the measured u52 ladder (8..724 limbs, the original fit file is unavailable; provenance is recorded in config/tuning/native-short.json):
    // the old fit overestimated u52 by 1.35-1.7x, pushing the u52/pq16 crossover down to 128 limbs (u52 is 39 % faster there).
    // constant 20.94 ns + 0.03388 ns per work unit at W1 (the W1 pressure term keeps its coefficient); the length term dropped.
    constexpr double co[]={20.944130,0,0,0.018296843,0.0038957815186156687,0.29861229267674327,2.2510469050552797};return short_dot(f,co);
}
inline double pq16_product_cost(const sbn3_mul_info &i,size_t an,size_t bn){
    if(i.workers==1&&an+bn>=256&&an+bn<=262144){
        // W1: the calibrated per-shape model (512..8192 limbs) extrapolates within 7 % to N = 2^17 (2026-09-09 forced
        // ladders, 23170..32768 limbs); the centered band above pays a measured factor (pow2 1.17, M3 1.20, M5 1.25, M7 1.35).
        const uint32_t N=uint32_t(i.transform_trunks/2),M=uint32_t(i.C);const bool cen=N>131072&&!(i.codec_mode&8u)&&i.trunk_bits==16;   // centered = the classic 16-bit codec beyond 2^17
        return pq16::native_cost({N,uint32_t(i.M2),M,cen,pq16::Recipe(i.codec_mode&7u),i.trunk_bits,(i.codec_mode&8u)!=0},an,bn);
    }
    const double N=i.transform_trunks/2.,n=i.M2,M=i.C,w=i.workers,lg=std::log2(n);
    const double tasks=M*std::max(1.,n/32768),fw=tasks/std::ceil(tasks/w),pw=M==1?std::min(w,std::max(1.,n/4096)):1,iw=M==1 && n>=8192?std::min(w,n/1024):1;
    const double cen=2*(an+bn)>131072,pressure=std::max(0.,std::log2((16/w)*(i.workspace_bytes+i.table_bytes+16.*(an+bn))/(64*1024*1024)));
    const double f[]={1,std::log2(w)+1,N*lg/fw,N*std::fmod(lg,3)/fw,N/iw,N/pw,N,N*(M==3),N*(M==5),N*(M==7),N*cen,N*cen/fw,N*pressure,N*std::max(0.,std::log2(16/w)),double(w>1 && M>1),double(w>1 && n>=8192)};
    constexpr double co[]={0,0,0.14743806599779716,0,0,0,0.87078610368689668,0.87742405870391149,1.0706828102670165,1.1366508820430412,1.6382975102983268,0,13.685158472707293,0.12003305563179904,1230.9830763656739,0};return short_dot(f,co);
}
inline double short_flat_cost(const sbn3_mul_info &i){
    // W1 (2026-09-09): the fit overestimates the measured flat ladder (23170..131072 limbs) by a flat 1.76x (range 1.54-1.84)
    const double w1=i.workers==1?0.567:1.;
    const double np=i.np,w=i.workers,M=i.M2,l=i.lbv,T=i.trunk_bits,full=i.full,waves=std::ceil(np/w),lg=std::log2(M);
    const double nv=double((i.nat+7)/8+(i.nyt+7)/8),cache=std::max(0.,std::log2(160*M/(768*1024))),mem=std::max(0.,std::log2((16/w)*(np*32*M+std::min(np,w)*128*M)/(64*1024*1024)));
    const double chunks=std::ceil(double(i.emit_trunks)/4096),ve=std::min(w,chunks),nc=std::ceil(48*np/52),e=l/ve;
    const double f[]={1,std::log2(w)+1,waves*nv*std::ceil(T/48),waves*std::max(0.,2*M-nv),waves*M*lg*full,waves*l*(lg+1)*(1-full),waves*l,waves*l*cache,waves*l*mem,e*(np==4?14:np*nc),e*i.digit_words,chunks/ve};
    constexpr double co[]={3590.5668741585941,0,1.6404783079099587,1.3410349690627057,0,0.73438534855920734,29.170559636210534,1.502248167796405,0,0.60909210705454486,0,0};return w1*short_dot(f,co);
}
}
