#pragma once
#include <algorithm>
#include <cmath>
namespace sbn::v3 {
// Saturated 16/W products, Zen5 Strix Halo, Clang 21.1.8; steady protocol.
// Generated by tools/generate_tuning.py from config/tuning/native-small.json.
// Calibration record SHA-256:
// 37b07b919c79720f65bbe8493a48d077d6b1b597975b87a6269becde797a3286
// Private common-TU policy only. These costs cannot grant legality.
inline double small_mul_cost(const sbn3_mul_info &i,bool fresh_mul=true){
    constexpr double co[]={0,969.15301140313716,0,0.034683333169339386,0,0.6469503873221526,0.12136349049540893,1.7204738973063822,0,0,83369.074688339751,8783.1379377567937,0,3.3780654907057794,0,2.6606394513460931,0,6072.5666719572409,0,801.02960994980742,1.6385691379824339,1.9974398206668722,0,1.0507154850654925,12.059769729551016,0,66618.061016198611,1549.8607882412841,2.2209128867345811,1.3328486729919857,1.7154050557737113,1.6246058465407205,3.1327498112383032,2.1948639152834413,35.913435933836382,0,12.20626534979162,0};
    constexpr double corr[]={-0.037614458860200116,-0.08604870371622253,-0.032932481925164486,-0.049074629211748821,0.031637471361375208,0.024167139832109205,0.0044825249807995829,-0.007082481284925125,-0.091624255101589114,0.17860939588412442,0.15534883468223981,0.10258571016089059,0.052269480015376069,-0.061855894123390556,-0.085758771545308393,-0.071130498218070784,0.0059862364787619761,0.0101680213586162,3.4557694250938586e-05,-0.074564694848055502,-0.171207537550568,-0.091210122943082464,-0.4125975669321022,-0.27499475590890532,-0.087727658628394919,0.086607658193451453,0.22067918041279475,0.24455724164703199,0.25052688184492133,-0.035183663596530169,0.13506552303032604,-0.0016347699789239301,0.45725770728005438,0.063500590793560116,0,0,0,0.089004013145993585,0.029216621418666433,0.083182026342234303,0.031583234318432914,-0.052610313737069453,0.1268651387057535,-0.11441471067145446,0.10174878620282898,-0.27326923305845446,-0.045775230702642743,0.026592724075496801,-0.1929965094975839,0.01112839588195335,-0.2507443248599811,-0.12049693031478889,0.013036798481159387,-0.21100543648441381,0.081627140426776171,-0.21187298001993549,-0.022371239684951225,0.041513381384207453,-0.06226862130322508,0.1927151682596088,-0.22826327524460424,0.13003583948007827};
    double f[38]{};const double np=i.np,T=i.trunk_bits,C=i.C,M=i.M2,l=i.lbv,lw=i.lbw,w=i.workers,nc=std::ceil(48*np/52);
    const double nv=double((i.nat+7)/8+(i.nyt+7)/8),lr=std::log2(M),lc=std::log2(C),full=i.full;
    if(i.algorithm==SBN3_MUL_FLAT){
        const double waves=std::ceil(np/w),cache=std::max(0.,std::log2(160*M/(768*1024))),mem=std::max(0.,std::log2((16/w)*(np*32*M+std::min(np,w)*128*M)/(64*1024*1024)));
        const double chunks=std::ceil(double(i.emit_trunks)/4096),ve=std::min(w,chunks),e=l/ve;
        const double a[]={1,std::log2(w)+1,waves*nv*std::ceil(T/48),waves*std::max(0.,2*M-nv),waves*M*lr*full,waves*l*(lr+1)*(1-full),waves*l,waves*l*cache,waves*l*mem,e*(np==4?14:np*nc),e*i.digit_words,chunks/ve};
        std::copy(a,a+12,f+26);
    }else{
        const double vr=std::min(w,std::max(1.,C/4)),vx=std::min(w,std::max(1.,C/64)),vt=std::min(w,std::max(1.,np*std::ceil(std::ceil(lw/2)/8))),ve=std::min(w,std::max(1.,C/i.fused_row_grain));
        const double work=np*C*lw/vt,tilebytes=4*(C+8)*64+C*(96+73+32),r=np*(C+i.fused_items)/ve,e=(C+i.fused_items)*l/ve;
        const double a[]={1,std::log2(w)+1,np,T*nv/vx,np*nv*std::ceil(T/48)/vr,np*std::max(0.,2*C*M-nv)/vr,np*2*C*M*lr/vr*full,np*C*l*(lr+1)/vr*(1-full),np*C/vr,np*2*C*M/vr*std::fmod(lr,3)*full,
            std::ceil(np/i.prime_batch),std::log2(w)+1,work,work*lc,work*std::fmod(lc,3),work*std::max(0.,std::log2(tilebytes/(512*1024))),
            1,std::log2(w)+1,np,r,r*M*lr*full,r*l*(lr+1)*(1-full),r*std::max(0.,M-lw),e*(np==4?14:np*nc),e*i.digit_words,r*l*std::max(0.,std::log2(np*M*64/(512*1024)))};
        std::copy(a,a+26,f);
    }
    double raw=0,correction=0;for(unsigned j=0;j<38;++j)raw+=co[j]*f[j];unsigned k=0;
    for(unsigned v:{4u,5u,7u,8u})correction+=corr[k++]*(i.np==v);
    for(size_t v:{64u,128u,512u,1024u,2048u})correction+=corr[k++]*(i.C==v);
    for(size_t v:{16u,32u,64u,128u,512u,1024u,2048u})correction+=corr[k++]*(i.M2==v);
    correction+=corr[k++]*full;
    for(size_t v:{64u,128u,512u,1024u,2048u})correction+=corr[k++]*(i.C==v?(w-1)/15:0);
    for(size_t v:{16u,32u,64u,128u,512u,1024u,2048u})correction+=corr[k++]*(i.M2==v?full:0);
    for(unsigned v:{1u,2u,4u,8u,16u})correction+=corr[k++]*(i.algorithm==SBN3_MUL_FLAT && i.workers==v);
    for(unsigned v:{4u,5u,7u,8u})correction+=corr[k++]*(i.np==v?full:0);
    for(unsigned v:{4u,5u,7u,8u})correction+=corr[k++]*(i.np==v?std::log2(w)/4:0);
    for(unsigned npv:{4u,5u,7u,8u})for(unsigned wv:{1u,2u,4u,8u,16u})correction+=corr[k++]*(i.algorithm==SBN3_MUL_FLAT && i.np==npv && i.workers==wv);
    const bool one_buffer=i.algorithm==SBN3_MUL_FLAT && i.M2>=16384 && i.per_worker_bytes<96*i.M2;
    const double packed=one_buffer?(i.workers==1?.90:i.workers==2?.84:.79):1.;
    const double tail=fresh_mul && i.algorithm==SBN3_MUL_FLAT && i.np==10 && i.M2==16384?(i.workers==4?.92:i.workers==8?.90:1.):1.;
    return raw*std::exp(correction)*packed*tail;
}
}
