#pragma once
#include <stddef.h>
namespace sbn::v3 {
// Native profile: Clang 21.1.8, Zen5 Strix Halo, W16 balanced LIN.
// Fit even indices only; odd indices and longer shapes are validation.
// Generated by tools/generate_tuning.py from config/tuning/native-deep.json.
// These costs never grant mathematical or resource legality.
inline constexpr const char *mul_tuning_profile="zen5-strix-halo-clang21.1.8-20260906-fit2";
inline constexpr unsigned default_crt(unsigned np){return np==4?1:2;}
inline constexpr unsigned default_codec(int T,size_t M2){return T>88 && M2<=2048?3:1;}
inline constexpr double mul_np_cost[]={0,0,0,0,1.0222737257650465,1.0090873188137273,1,0.99985598922003172,0.9893461130384632};
inline constexpr double mul_m2_cost(size_t value){
    switch(value){case 1024:return 1.023175826518707;case 4096:return 0.99561430590565647;case 8192:return 0.99058618518236097;case 16384:return 1.2249600702432439;default:return 1.;}
}
inline constexpr double mul_column_cost(size_t value){
    switch(value){case 1024:return 0.98081225175260889;case 4096:return 1;case 8192:return 0.98121726508358853;default:return 1.;}
}
inline constexpr double mul_codec_cost(unsigned T){return T==84?1.0038992667635309:1.;}
inline constexpr double mul_large_rows_cost(unsigned np,size_t M2){
    if(M2!=8192)return 1.;
    switch(np){case 7:return 1.0418083640839255;case 8:return 1.0870642120914775;default:return 1.;}
}
}
